pipeline:
  ecr:
    image: plugins/ecr
    registry: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com
    repo: expressive
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags: ${DRONE_COMMIT_SHA:0:8}
    file: Dockerfile
    region: ap-southeast-2
  rancher:
    image: peloton/drone-rancher
    url: https://rancher.travlrdev.com
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: expressive/expressive
    docker_image: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com/expressive:${DRONE_COMMIT_SHA:0:8}
    confirm: true
    timeout: 180
